---
version: '3.7'
services:

  wordpress:
    image: wordpress:${WORDPRESS_VERSION:-php7.4-fpm}
    container_name: wordpress
    volumes:
    # - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
    - ./wordpress:/var/www/html
    environment:
    - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME:-wordpress}
    - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX:-wp_}
    - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST:-mysql}
    - WORDPRESS_DB_USER=${WORDPRESS_DB_USER:-root}
    - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD:-password}
    links:
    - mysql:mysql
    - manticore:manticore
    depends_on:
    - mysql
    - manticore
    restart: always

  manticore:
   image: manticoresearch/manticore:latest
   container_name: manticore
   ports:
   - 19312:9312   

  mysql:
    image: mysql:${MYSQL_VERSION:-5.7}
    container_name: mysql
    volumes:
    - db-data:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
    - MYSQL_USER=${MYSQL_USER:-root}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
    - MYSQL_DATABASE=${MYSQL_DATABASE:-wordpress}
    restart: always

  nginx:
    image: nginx:${NGINX_VERSION:-latest}
    container_name: nginx
    ports:
    - '80:80'
    - '443:443'
    volumes:
    - ${NGINX_CONF_DIR:-./nginx}:/etc/nginx/conf.d
    - ${NGINX_LOG_DIR:-./logs/nginx}:/var/log/nginx
    - ${WORDPRESS_DATA_DIR:-./wordpress}:/var/www/html
    - ${SSL_CERTS_DIR:-./certs}:/etc/letsencrypt
    - ${SSL_CERTS_DATA_DIR:-./certs-data}:/data/letsencrypt
    depends_on:
    - wordpress
    restart: always

  adminer:
    image: adminer
    restart: always
    links:
    - mysql
    ports:
    - 8080:8080

  backup:
    image: zeenlym/mariadb-backup
    container_name: ${NAMESPACE}_backup
    depends_on:
    - mysql
    restart: unless-stopped
    environment:
    - TIMEZONE=${TIME_ZONE}
    - SCHEDULE=0 0 3 * *
    - BACKUP_METHOD=mysqldump
    - MYSQL_HOST=mysql
    - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
    - MYSQL_USER=${WORDPRESS_DB_USER}
    - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
    volumes:
    - ${MYSQL_BACKUP_DIR}:/backup
    restart: unless-stopped

volumes:
  cache-data:
  public-data:
  db-data:
